### ISSUE TITLE
音量调节问题

### ISSUE THREAD

**Issue by toutoumu** [RelinRan/IJKPlayer#1]
1. 手指按下
2. 向下滑动，再上下滑动，音量之后变小，不会向上滑动变大，向下滑变小

**Comment by RelinRan** [comment]
2024.3.5.1版本已更新为ffm4.0 版本，操作控制也已更新

**Comment by toutoumu** [comment]
仔细看了您的代码, 代码中没有判断是否一根手指按下的情况下启用,音量,亮度,进度调节, 这样可能会带来意想不到的情况

**Comment by RelinRan** [comment]
谢谢提醒，新版本处理该问题
