### ISSUE TITLE
如何在播放状态下切换视频显示比例

### ISSUE THREAD

**Issue by JcTom** [RelinRan/IJKPlayer#3]
如果已经在播放状态了，怎么设置切换播放显示比例？比如16:9、4:3等等，要重新初始化播放器？

**Comment by RelinRan** [comment]
VideoView.setVideoDisplaySize(int displayWidth, int displayHeight);方法可以直接设置想要的宽高；
同时setVideoListener监听中onVideoSizeChanged(iMediaPlayer, width, height, sarNum, sarDen)有返回加载完成时，原视频的宽高。
