### ISSUE TITLE
rtmp直播视频流没有声音

### ISSUE THREAD

**Issue by SkyCJC** [RelinRan/IJKPlayer#4]

**Comment by RelinRan** [comment]
> _No description provided._

rtmp://liteavapp.qcloud.com/live/liteavdemoplayerstreamid  我测试是有声音的，是不是你的直播音频是经过特殊处理加密过的。

**Comment by SkyCJC** [comment]
视频流是h265编码的，如果是普通加密的音频，需要怎么处理
